### ISSUE TITLE
Can't use query long strings

### ISSUE THREAD

**Issue by dan-online** [fwextensions/quick-score#8] opened 2020-08-21 06:50 UTC
I have a lot of input data and so I've been using quick-score to sort by query quickly as opposed to fuse.js and I've found that it works great until the string goes over 150 characters till which it hangs and never finishes. 

Is there a config method I could set or is this just a bug?

Much appreciated

Dan

My code:
```js
const { QuickScore } = require("quick-score");
const qs = new QuickScore(array, ["title", "url"]); // array is about 500-1000 items long and grows over time
qs.search("test") // about 2-9ms
qs.search("really long test") // never finishes
```

Possible place why:
[/src/config.js](https://github.com/fwextensions/quick-score/blob/master/src/config.js#L18)

**Comment by fwextensions** [comment] 2020-08-24 02:57
Is your code somewhere I could take a look?  Have you tried playing with the [demo page](https://fwextensions.github.io/quick-score-demo/)?  When I type 20 - 30 character strings, even with 1200 items (well, 2400, since the query is run on two copies of the list), it isn't bad.

**Comment by dan-online** [comment] 2020-08-24 19:55
Yea it's quite weird, I have around 5000 inputs and when I do limit it down it tends to crash less but at 5000 it takes an insanely long time just one char over 15 which I found quite odd

**Comment by fwextensions** [comment] 2020-08-30 01:10
I can somewhat reproduce this issue.  Long queries that don't match anything are generally fast.  It's the long queries that match up to the last character or two that seem to really slow things down, but only when there are several thousand items to search.  I'm investigating what could be done about that.

**Comment by dan-online** [comment] 2020-09-09 13:12
Thanks that would be awesome!

**Comment by Slapbox** [comment] 2021-03-31 20:08
100% reproducibility for me in the demo if I type, "adding audio to web apps -"

It goes from super fast to never finishes with the addition of a single character, the dash.

I first noticed this freezing intermittently in our own project, and when I became certain it was QuickScore, I went to the demo to do some testing. Sure enough, the character that froze our app is an equals sign. It seems like special characters maybe cause this issue.

If you instead type, "adding audio to web - tele" then the search will complete, but it takes over 100ms.

If you type, "adding audio to web - telerik developer" it will complete but take about a second. It also won't produce the expected result in the list, while QuickSilver does (because in the list it's -telerik, no space.)

It seems also like your finding that matching up to the final character causes the issue in some cases, but I'm not sure what the exact requirements are. It seems like the string has to be at least 20 characters to produce the issue.

Perhaps some of the logic could be dropped for longer strings if that's necessary to prevent freezes?

Thank you for sharing this awesome project @fwextensions! The demo is really excellent at showcasing the benefits of this package over the competition. I'd love to know if you've run into this bug again and if there are any plans to try to address this issue?

**Comment by Slapbox** [comment] 2021-03-31 20:30
Would it make sense to do a search of the list items for exact matches first, using something like `myString.includes(searchValue)`, and then exclude those items from the more intensive processing? I'm not entirely sure what logic is causing the slowdown yet.

**Comment by Slapbox** [comment] 2021-04-02 22:15
@fwextensions, if you think running `string.indexOf(searchVal)` as a pre-flight check might remedy this, would you be open to a PR that does that?

**Comment by fwextensions** [comment] 2021-04-03 01:56
Calling `indexOf()` won't help, as searching for `gh` should return `GitHub`, but the former is not a substring of the latter.

I think the algorithm may be running into some limits around recursion.  When the query exactly matches part of a string, adding a character that doesn't match can trigger a lot of recursion, as the algorithm keeps trying shorter and shorter parts of the query, all of which do match.  But then it keeps building up to the new character that doesn't match, and so it loops again.

I would like the search to not completely lock up with long, nearly matching queries but I'm also not sure it's really much of a problem in the real world, as users tend to stop typing once they've found the thing they want.

**Comment by bldng** [comment] 2021-04-03 14:54
Just a note: I ran into this issue because of a real word problem: Users were pasting longer names (complete titles) in the input field, presumably from a pdf. Instead of the expected single result they got a crash which is now temporarily avoided by restricting the character length.

**Comment by Slapbox** [comment] 2021-04-03 18:23
Thanks for your reply @fwextensions. I know the main use of this library is in QuicKey, and I can imagine it never causes any issues there, but it definitely causes issues in the real world in our context. 

Our scenario is very similar to @bldng's scenario where a user pastes a string that's say 20 or more characters long - and then maybe hits one more key - seemingly especially problematic if that key is a special character. We don't have that many strings for searching, nor are they very long strings - and in 99% of cases we're seeing no issues at all - but then suddenly one seemingly innocuous string freezes the page indefinitely.

That sort of situation is why I thought that perhaps doing an `indexOf()` to check for exact matches first might be worth it. I'm proposing that only for longer strings though - like 15 characters or more. In that case the `gh` should match `GitHub` shouldn't pose any problems that I can see. Maybe I'm wrong? I'm thinking like:

1. Check `searchValue` length
2. If `searchValue` > 15 characters, try `indexOf(searchValue)`
3. If we get an index >-1 (exact match) we now don't need to run the QuickScore algorithm - hopefully preventing the edge case where recursion can lead to exponential slowdowns. Instead we return `results {matches: [startIndex, startIndex+ searchValue.length]}`
4. If we don't get an exact match, run QuickScore as usual. Exponential slowdowns could still occur - but hopefully the `indexOf` check will weed out almost all of those cases.

So I definitely agree that without step 2, then it would totally mangle QuickScore's results. But if we only did this for longer strings, is there some shortcoming I'm overlooking?

**Comment by Slapbox** [comment] 2021-04-03 19:05
So after confirming that the issue is the `calcScore` recursion - it seems like the best approach would be to limit recursions to X and simply return a score of `0` after we reach that recursion limit. This will still result in slowdowns, but avoid outright freezes unless a user just keeps typing and typing even after they're already failing to match anything.

It's not perfect but I think it's a good protection against freezing. The number of recursions could be hardcoded, user configurable, or we could dynamically guess a best value based on the length of the searchValue and string to search.

What do you think @fwextensions?

**Comment by fwextensions** [comment] 2021-04-04 02:55
So it looks like in the worst case, a partially-matching query can generate `2 ^ querySubstringMatchLength` recursive calls and `(2 ^ queryLength) - 1` iterations through the `for i` loop in `quickScore()`.  

As an example, if the string is `"abcdefghijklmnopqrstuvwxyz"` and the query is `"abcdefghijklmnopqrstuvwxy0"`, it'll generate  33,554,432 recursive calls and 67,108,863 loops before returning a 0 score.

The tricky thing is that sometimes the way the algorithm breaks down the query to recur on smaller strings is important for catching cases where part of the query is included towards the end of the string, but the whole query is included in a more spread out form.  So scoring `"abcxyz"` against `"a|b|c|x|y|zabcxy"` will match part of the query against the end of the string, but then it needs to score each character in the query against the string to finally get a match.

Having some fixed recursion limit could help, but I think there's also a way to reduce the number of calls based on whether all of the remaining query characters exist in the rest of the search string.  Need to play around with it some more.

**Comment by Slapbox** [comment] 2021-04-05 18:44
Thanks for the mini write-up @fwextensions! That's really helpful. The fixed recursion limit is definitely not the best mitigation technique, but it's the best I can see thus far since I'm not yet really comprehending how all the logic works yet.

I'd be really interested in seeing this problem fixed, because besides this issue, QuickScore definitely seems to be the best fuzzy matching library!

**Comment by fwextensions** [comment] 2021-04-17 19:36
I've got a "fix" on [this branch](https://github.com/fwextensions/quick-score/tree/feature/2021/long-queries).  It just counts all the iterations of the inner loop and bails when it hits 5000 (which can be changed via the `config` param).  Definitely a kludge, but I wasn't able to come up with anything more elegant.  It avoids the slowdown from long near matches, though.

**Comment by dan-online** [comment] 2021-04-19 10:49
Thought I'd add some extra information, this image I took on the demo site after copy pasting the objects in the json field a few times to have a bit larger of a dataset. My page froze as I typed an "R":

![image](https://user-images.githubusercontent.com/41877062/115224781-96b4a500-a10d-11eb-89ef-a323bac4fe1d.png)

**Comment by Slapbox** [comment] 2021-04-19 17:56
@fwextensions that sounds awesome! 

I haven't had a chance to test that out yet - but in my own testing of recursions (around when I suggested it, using the quick-score-demo repo) I found that 150 recursions seemed to be the most that would avoid multi-second slowdowns. 

I think having a higher default like the 5000 is advisable - but I wanted to share my findings for anyone else who comes across this. Also though, my hacky test code was not identical to what @fwextensions has implemented so use my numbers only as a ballpark.

**Comment by fwextensions** [comment] 2021-04-20 23:08
@dan-online I suspect you typed some additional character after the `R`, as I'm not able to reproduce the issue with just that query, which fully matches those items.  It's not the total number of items that's a problem (though it can make it slightly worse); it's the long, nearly-matching query that triggers `2^n` loops.

@Slapbox it seems to not be an issue of the recursion depth.  It's more about the number of loops exploding when a long query matches except for the last character.  A 5K vs. 50K limit won't make much difference.  It's when you get in the 50M range that the browser starts locking up.

One disadvantage of limiting the iterations is that it'll return 0 when there should be a match, like:

    string: "a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|zabcdefghijklmnopqrstuvwxy1"
    query:  "abcdefghijklmnopqrstuvwxyz"

It's a bit of an artificial example, though, so it's still probably better to avoid locking up the UI by returning an incorrect score.

**Comment by Slapbox** [comment] 2021-04-21 22:35
@fwextensions thanks for the detailed explanations and for the work you've done to make this great library you're sharing even better (and obviously thanks for sharing it in the first place too!)

**Comment by Slapbox** [comment] 2021-04-21 23:41
I've gotten a chance to give the new version a try and it seems to work great! I've not tested it exactly the same way as I tested the previous version - but I think it's working and stable. It would be great to see this merged into the `master` branch. 

Right now there's the minor downside that Yarn doesn't run the `postinstall` on files installed from git branches, so the files in `node_modules` aren't ready to go - but it's definitely working well so far besides that!

**Comment by Slapbox** [comment] 2021-04-23 21:25
@fwextensions when do you think you might release version (presumably) 0.12.0 to npm? Still working great for us, besides the little package manager hiccup caused by depending directly on a Github commit.

**Closed** 2021-04-25 01:06 UTC

**Comment by fwextensions** [comment] 2021-04-25 02:25
Just pushed it to npm a few minutes ago.  I upped the `maxIterations` to `2^16`, which seemed like a nice round number.  So 16-character edge-case queries will still return a correct score after 65K loops, which didn't seem noticeably slower than the 5K limit.

I haven't properly documented the `config` param yet, but if you wanted to change the limit, you could do something like:

    new QuickScore(items, { config: { maxIterations: Math.pow(2, 10) }})

Given how the algorithm works, powers of 2 are the most efficient limits.

**Comment by Slapbox** [comment] 2021-04-25 18:11
@fwextensions thank you so much for your research, hard work, and advice!

**Comment by dan-online** [comment] 2021-04-27 05:06
@fwextensions Thanks for all the information and the new version which works great!
